Angular 17 to 18 update
finos/traderX pull request #199
Opened 2024-07-16 14:41 UTC by mimiflynn

2024-07-16 14:44 UTC, mimiflynn commented
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE FINOS Corporate Contributor License Agreement.

THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

2024-09-01 03:45 UTC, DovOps commented
Thanks Mimi.  This compiles but does not build due to ag-grid compatibility isues with angular 18.  I'm moving the ag-grid changes in here (originally part of PR #207  ).

2024-09-01 04:38 UTC, DovOps requested changes
See other comments

2024-09-01 04:38 UTC, DovOps commented on web-front-end/angular/package.json
ngx-bootstrap should also move to 18..

2024-09-01 04:38 UTC, DovOps commented on web-front-end/angular/package.json
See my PR to your branch which will migrates ag-grid and ngx-bootstrap. Tested this all locally.

2024-09-01 04:38 UTC, DovOps commented on web-front-end/angular/package.json
See https://github.com/mimiflynn/traderX/pull/1

2024-09-02 19:59 UTC, DovOps approved these changes

2024-09-03 21:13 UTC, DovOps commented
Merged via https://github.com/finos/traderX/pull/214

2024-09-03 21:13 UTC, closed without merging