Improve developer experience when working with traderx and k8s
finos/traderX pull request #232
Opened 2024-10-15 19:44 UTC by matthewgardner

- All services in gitops yaml using prebuilt images from GH container reg
- Ability to cherry pick which images to build locall
- position service now using multi-stage build (1.5GB to 0.5 GB)
- position service add simple "ready" and "alive" end points for health endpoints
- position service deployment config added for health end points
- Updated read me

2024-10-17 10:15 UTC, rocketstack-matt requested changes
Running `tilt up` on a clean Minikube install, I see 7 services installed then start getting a bunch of errors in the tilt logs

```
account-serv… │ 
database-dep… │ 
   trade-feed │ 
people-servi… │ 
ERROR: Cluster status error: cluster liveness check: Get "https://127.0.0.1:57632/livez?timeout=10s": http2: client connection lost
database-dep… │ Error streaming database-deployment-7cb9448875-bh7vz logs: http2: client connection lost
account-serv… │ Error streaming account-service-6d77694d57-gwgqv logs: http2: client connection lost
people-servi… │ Error streaming people-service-c76d9fcf4-4w7lb logs: http2: client connection lost
   trade-feed │ Error streaming trade-feed-fdd548bd-rp4hl logs: http2: client connection lost
database-dep… │ Error streaming database-deployment-7cb9448875-lkwn5 logs: http2: client connection lost
position-ser… │ Error streaming position-service-67c9969bb4-drrgn logs: Get "https://127.0.0.1:57632/api/v1/namespaces/traderx/pods/position-service-67c9969bb4-drrgn/log?container=position-service&follow=true&sinceTime=2024-10-17T10%3A12%3A40Z": net/http: TLS handshake timeout
account-serv… │ Error streaming account-service-6d77694d57-gwgqv logs: Get "https://127.0.0.1:57632/api/v1/namespaces/traderx/pods/account-service-6d77694d57-gwgqv/log?container=account-service&follow=true&sinceTime=2024-10-17T10%3A12%3A40Z": net/http: TLS handshake timeout
database-dep… │ Error streaming database-deployment-7cb9448875-lkwn5 logs: Get "https://127.0.0.1:57632/api/v1/namespaces/traderx/pods/database-deployment-7cb9448875-lkwn5/log?container=database-app&follow=true&sinceTime=2024-10-17T10%3A12%3A40Z": net/http: TLS handshake timeout
database-dep… │ Error streaming database-deployment-7cb9448875-bh7vz logs: Get "https://127.0.0.1:57632/api/v1/namespaces/traderx/pods/database-deployment-7cb9448875-bh7vz/log?container=database-app&follow=true&sinceTime=2024-10-17T10%3A12%3A40Z": net/http: TLS handshake timeout
people-servi… │ Error streaming people-service-c76d9fcf4-4w7lb logs: Get "https://127.0.0.1:57632/api/v1/namespaces/traderx/pods/people-service-c76d9fcf4-4w7lb/log?container=people-service&follow=true&sinceTime=2024-10-17T10%3A12%3A40Z": net/http: TLS handshake timeout
   trade-feed │ Error streaming trade-feed-fdd548bd-rp4hl logs: Get "https://127.0.0.1:57632/api/v1/namespaces/traderx/pods/trade-feed-fdd548bd-rp4hl/log?container=trade-feed&follow=true&sinceTime=2024-10-17T10%3A12%3A40Z": net/http: TLS handshake timeout
```

Screenshot attached.
![Screenshot 2024-10-17 at 11 15 10](https://github.com/user-attachments/assets/169de876-f019-4f09-a714-2653c4c5f960)

2024-10-30 15:02 UTC, matthewgardner commented
> Running `tilt up` on a clean Minikube install, I see 7 services installed then start getting a bunch of errors in the tilt logs
> 
> ```
> account-serv… │ 
> database-dep… │ 
>    trade-feed │ 
> people-servi… │ 
> ERROR: Cluster status error: cluster liveness check: Get "https://127.0.0.1:57632/livez?timeout=10s": http2: client connection lost
> database-dep… │ Error streaming database-deployment-7cb9448875-bh7vz logs: http2: client connection lost
> account-serv… │ Error streaming account-service-6d77694d57-gwgqv logs: http2: client connection lost
> people-servi… │ Error streaming people-service-c76d9fcf4-4w7lb logs: http2: client connection lost
>    trade-feed │ Error streaming trade-feed-fdd548bd-rp4hl logs: http2: client connection lost
> database-dep… │ Error streaming database-deployment-7cb9448875-lkwn5 logs: http2: client connection lost
> position-ser… │ Error streaming position-service-67c9969bb4-drrgn logs: Get "https://127.0.0.1:57632/api/v1/namespaces/traderx/pods/position-service-67c9969bb4-drrgn/log?container=position-service&follow=true&sinceTime=2024-10-17T10%3A12%3A40Z": net/http: TLS handshake timeout
> account-serv… │ Error streaming account-service-6d77694d57-gwgqv logs: Get "https://127.0.0.1:57632/api/v1/namespaces/traderx/pods/account-service-6d77694d57-gwgqv/log?container=account-service&follow=true&sinceTime=2024-10-17T10%3A12%3A40Z": net/http: TLS handshake timeout
> database-dep… │ Error streaming database-deployment-7cb9448875-lkwn5 logs: Get "https://127.0.0.1:57632/api/v1/namespaces/traderx/pods/database-deployment-7cb9448875-lkwn5/log?container=database-app&follow=true&sinceTime=2024-10-17T10%3A12%3A40Z": net/http: TLS handshake timeout
> database-dep… │ Error streaming database-deployment-7cb9448875-bh7vz logs: Get "https://127.0.0.1:57632/api/v1/namespaces/traderx/pods/database-deployment-7cb9448875-bh7vz/log?container=database-app&follow=true&sinceTime=2024-10-17T10%3A12%3A40Z": net/http: TLS handshake timeout
> people-servi… │ Error streaming people-service-c76d9fcf4-4w7lb logs: Get "https://127.0.0.1:57632/api/v1/namespaces/traderx/pods/people-service-c76d9fcf4-4w7lb/log?container=people-service&follow=true&sinceTime=2024-10-17T10%3A12%3A40Z": net/http: TLS handshake timeout
>    trade-feed │ Error streaming trade-feed-fdd548bd-rp4hl logs: Get "https://127.0.0.1:57632/api/v1/namespaces/traderx/pods/trade-feed-fdd548bd-rp4hl/log?container=trade-feed&follow=true&sinceTime=2024-10-17T10%3A12%3A40Z": net/http: TLS handshake timeout
> ```
> 
> Screenshot attached. ![Screenshot 2024-10-17 at 11 15 10](https://private-user-images.githubusercontent.com/66839492/377420178-169de876-f019-4f09-a714-2653c4c5f960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDA2MDEsIm5iZiI6MTczMDMwMDMwMSwicGF0aCI6Ii82NjgzOTQ5Mi8zNzc0MjAxNzgtMTY5ZGU4NzYtZjAxOS00ZjA5LWE3MTQtMjY1M2M0YzVmOTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE0NTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYTFjMDM2YzQwOWI4YjVmMTNlN2RjNWZjNjI0YzBjNmRiNjFmY2MyMDFiZTVhY2FhMTYwYzdiN2MyNGFhM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rPwAcZ8YnxUFhw_xwMQMjUV6WzmvIaqb35nivufH-9I)

Was your cluster still accessible? It looks like you minikube died `Cluster status error: cluster liveness check: Get "https://127.0.0.1:57632/livez?timeout=10s": http2: client connection lost`

2024-10-30 15:18 UTC, matthewgardner commented
If anyone wants to trial this - its actually a good example of how you can do live development changes and break fixing with code.

Getting started:
- Following the instructions and install Docker, k8s (perhaps as docker for desktop) and install tilt.dev
- Install an ingress controller e.g. `kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/cloud/deploy.yaml`
- Check out the code and navigate to the subfolder `./gitops/local` and run `tilt up`

This should run start all the services using the pre-built images from GHCR (note - this will take time to download as their all about 1.5GB each!!!) HOWEVER, the position service will keep crashing because I have added health and liveliness end points to the configuration that don't exist in the pre-built image (not until this PR gets merged as they're also included in the PR).

How to fix? We need to use a locally built image (assuming the PR isn't merged).

Next steps:
- In the tiltfile uncomment the line for the position service `docker_build('ghcr.io/finos/traderx/position-service', './../../position-service/.')` 

Uncommenting this line will force tilt.dev to reload the tiltfile and instruct tilt.dev to build this image from your local machine. The image will then be used in your k8s cluster instead of the massive 1.5GB image - the new multistage build, with health end points is only around 0.5GB. 

After the image has been built it should take a few seconds of the health endpoints to be called and the pod to be marked as ready. Everything should be working!!!! 

![image](https://github.com/user-attachments/assets/87954a89-e38a-496d-b49b-4594283e637c)

2025-01-24 13:47 UTC, DovOps approved these changes
I've reviewed this and run this locally. Per our discussion on #252  this is worth merging in as-is and we can continue to get the other pieces in place.

2025-01-24 13:48 UTC, merged